apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: max-map-count-setter
  namespace: elastic-system
spec:
  selector:
    matchLabels:
      name: max-map-count-setter
  template:
    metadata:
      labels:
        name: max-map-count-setter
    spec:
      initContainers:
        - name: max-map-count-setter
          image: docker.io/bash:5.2.15
          securityContext:
            privileged: true
            runAsUser: 0
          command:
            [
              "/usr/local/bin/bash",
              "-e",
              "-c",
              "echo 262144 > /proc/sys/vm/max_map_count",
            ]
      containers:
        - name: sleep
          image: docker.io/bash:5.2.15
          command: ["sleep", "infinity"]
